name: Auto Commit Immediately

on:
  workflow_dispatch: # Cho phép kích hoạt thủ công từ giao diện GitHub

jobs:
  auto_commit:
    name: "Auto push a commit to my repo"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout repository

      - name: Set up Git user
        run: |
          git config --global user.name "Automated Committer"
          git config --global user.email "committer@example.com"

      - name: Make a change to report.txt
        run: |
          echo "Automated commit at $(date)" >> report.txt  # Thêm dòng mới vào file report.txt

      - name: Commit and push
        run: |
          git add report.txt
          git commit -m "Automated commit at $(date)"
          git push
